### ISSUE TITLE
master crashes on startup

### ISSUE THREAD

**Issue by carnager** [ambientsound/pms#90] opened 2017-08-26 13:28 UTC
debug output of pms command. let me know if you need more info

```
[0.00521] Starting Practical Music Search.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=1 addr=16 pc=93986231718251]

goroutine 16 [running]:
runtime.gopanic
	/build/gcc/src/gcc/libgo/go/runtime/panic.go:493

	:0
github_com_ambientsound_pms_widgets.Start.pN38_github_com_ambientsound_pms_widgets.UI
	/home/carnager/go/src/github.com/ambientsound/pms/widgets/ui.go:107
github_com_ambientsound_pms_pms.setupUI.pN35_github_com_ambientsound_pms_pms.PMS
	/home/carnager/go/src/github.com/ambientsound/pms/pms/setup.go:74
github_com_ambientsound_pms_pms.New
	/home/carnager/go/src/github.com/ambientsound/pms/pms/setup.go:42
main.main
	/home/carnager/go/src/github.com/ambientsound/pms/main.go:74
runtime_main
	/build/gcc/src/gcc/libgo/runtime/proc.c:606
```

**Comment by ambientsound** [comment] 2017-08-29 10:15
This looks like a duplicate of #66. Which terminal emulator are you using?

**Comment by ambientsound** [comment] 2017-08-29 15:51
Duplicate of #66.

**Closed** 2017-08-29 15:51 UTC
Labels: Bug, Go
