### ISSUE TITLE
'add-to' becomes 'add'

### ISSUE THREAD

**Issue by meetyourlaser** [ambientsound/pms#13] opened 2015-08-05 11:21 UTC
If one doesn’t select a playlist when using <code>add-to</code>, and instead change to the playlist or library window, the next time <code>add-to</code> is being used it acts like <code>add</code>
I came over this when I didn’t want to add the song to an playlist after all. What about an “Cancel”-option above or under the list of playlists?

**Comment by ambientsound** [comment] 2015-08-30 09:53
I am unable to reproduce this error. It might have been fixed unintentionally as part of the code refactor done recently.

Can you see if you experience this error with the latest git master?

**Comment by riggs-** [comment] 2022-08-14 10:09
The legacy branch is no longer maintained, closing for now.

**Closed by riggs-** 2022-08-14 10:09 UTC
Labels: Bug, Legacy
