### ISSUE TITLE
Nil pointer dereference on startup

### ISSUE THREAD

**Issue by mpldr** [ambientsound/pms#122] opened 2019-12-07 22:07 UTC
Terminal Emulator: Alacritty
Version: 93ed7dd

Error Message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a9d3f]
goroutine 88 [running]:
github.com/ambientsound/pms/index.(*Index).IndexFull(0x0, 0xfc4c38, 0x0, 0x0, 0xc000476070, 0x0, 0x0)
    /tmp/pms/index/index.go:175 +0xdf
github.com/ambientsound/pms/songlist.(*Library).ReIndex.func1(0xc00016e360)
    tmp/pms/songlist/library.go:109 +0x7f
created by github.com/ambientsound/pms/songlist.(*Library).ReIndex
    /tmp/pms/songlist/library.go:107 +0x92
```
I reformatted it so it's easier readable. In the Terminal it's shifted all around.

Steps to reproduce:
execute `pms` in the terminal

**Comment by ambientsound** [comment] 2019-12-10 14:09
Closing as a duplicate of #66.

**Comment by ambientsound** [comment] 2019-12-26 17:15
Hi @poldi1405,

I am unable to reproduce this error so I added some debugging statements to try to diagnose your problem. Could you try running the latest master with the following command-line flags?

```
pms --debug=debug.log
```

Please include the log in the issue, then I can look into it.

**Comment by riggs-** [comment] 2022-08-14 09:41
Feedback timeout. Closing.

**Closed by riggs-** 2022-08-14 09:41 UTC
Labels: Bug
